//
//  CodeGenerator.swift
//  Parser
//
//  Created by Christian Lundtofte on 28/10/2016.
//  Copyright © 2016 Christian Lundtofte. All rights reserved.
//

import Foundation


/*
    Every function creates a string containing for example function calls, types and such. 
    The program is generated by creating all types and functions.
*/
class CodeGenerator {
    private var internalCode:String = ""
    private var program:ProgramNode?
    private var doingMainBlock = false
    
    // Prototyper
    private var declaredFunctions:[String] = []
    
    // Direct conversions, used when possible (Not user-defined types) (Types and operators)
    private var typeConversions:[String: String] = ["Int":"int", "Char":"char", "Float":"float", "String":"std::vector<char>", "Bool":"bool", "Generic":"T"]
    private var opConversions:[String: String] = ["AND":"&&", "OR":"||"]
    
    
    init(program: ProgramNode) {
        self.program = program
    }
    
    // MARK: General functions
    // Creates and saves code at ~/Desktop/intermediate.cpp
    func generate() {
        guard let program = self.program else { return }
        
        
        // Create standard lib, prototypes, types and functions
        
        // Stdlib
        var stds = ""
        do {
            if let path = Bundle.main.path(forResource: "std", ofType: "cpp") {
                let stdFuncs = try String(contentsOfFile: path)
                stds += stdFuncs
            }
        }
        catch { }
        
        
        let functions = program.functions
        let objTypes = program.types
        
        var typeString = ""
        var funcsString = ""
        
        // Generate types
        for objType in objTypes {
            typeString += createObjectType(objType: objType)
        }
        
        
        // Generate functions
        for function in functions {
            funcsString += createFunction(function: function)
        }
        
        // Prototypes
        var decls = ""
        for dec in declaredFunctions {
            decls += dec+";\n"
        }
        
        emit(stds)
        
        emit("\n// Prototypes \n")
        emit(decls)
        
        emit("\n// Types: \n")
        emit(typeString)
        
        emit("\n// Functions: \n")
        emit(funcsString)
        
        //print("Code:")
        //print(internalCode)
    }
    
    func getIntermediate() -> String {
        return self.internalCode
    }
    
    private func emit(_ str: String) {
        internalCode += str
    }
    
    // MARK: Type declarations
    // Generates a type declaration
    private func createObjectType(objType: ObjectTypeNode) -> String {
        guard let name = objType.name else { return "" }
        var ret = ""
        
        // Type declaration
        var typeDecl = "struct t_"+name+" {\n"
        
        for v in objType.variables {
            guard let ttype = v.type, let vname = v.identifier else { continue }
            
            // Normal type
            if ttype is NormalTypeNode {
                guard let ttype = ttype as? NormalTypeNode else { return "" }
                
                let type = createTypeString(type: ttype)
                typeDecl += " "+type+" "+vname+";\n"
            }
            else if ttype is FunctionTypeNode { // Function type
                guard let ttype = ttype as? FunctionTypeNode else { return "" }
                
                let typeString = createFunctionTypeString(type: ttype)
                typeDecl += " "+typeString+" "+vname+";\n"
            }
            
            
        }
        
        typeDecl += "};"
        ret += typeDecl
        
        declaredFunctions.append("struct t_"+name)
        
        // Initialization function
        
        // Function definition
        var typeInit = "t_"+name+" "+name+"("
        for n in 0 ..< objType.variables.count {
            let v = objType.variables[n]
            guard let ttype = v.type, let vname = v.identifier else { continue }
            
            if ttype is NormalTypeNode {
                guard let ttype = ttype as? NormalTypeNode else { return "" }
                let type = createTypeString(type: ttype)
                typeInit += type+" "+vname
            }
            else if ttype is FunctionTypeNode {
                guard let ttype = ttype as? FunctionTypeNode else { return "" }
                
                let typeString = createFunctionTypeString(type: ttype)

                typeInit += typeString+" "+vname
            }
            
            if n != objType.variables.count-1 {
                typeInit += ", "
            }
        }
        typeInit += ")"
        
        declaredFunctions.append(typeInit)
        
        // Function block
        typeInit += " {\n"
        
        typeInit += "t_"+name+" t_tmp;"
        for n in 0 ..< objType.variables.count {
            let v = objType.variables[n]
            guard let vname = v.identifier else { continue }
            
            typeInit += "t_tmp."+vname+" = "+vname+";\n"
        }
        
        typeInit += "return t_tmp;"
        
        typeInit += "}\n"
        
         ret += "\n"+typeInit
        
        return ret
    }

    
    // MARK: Function declarations
    // Generates a function declaration
    private func createFunction(function: FunctionNode) -> String {
        guard let retType = function.retType,
            let identifier = function.identifier,
            let block = function.block else { return "" }
        
        
        let genCheck = TreeHelper.isGenericFunction(node: function)
        if genCheck {
            return createGenericFunction(function: function)
        }
        else {
            var ret = ""
            
            if identifier == "main" { // Main has some special parameters (arguments)
                let declaredFunction:String = "int main(int argc, char *argv[])"
                declaredFunctions.append(declaredFunction)
                
                doingMainBlock = true
                let funcDecl:String = "\n"+declaredFunction+createBlock(block: block)
                ret += funcDecl
            }
            else {
                var type = ""
                if retType is NormalTypeNode {
                    type = createTypeString(type: retType as! NormalTypeNode)
                }
                else if retType  is FunctionTypeNode {
                    type = createFunctionTypeString(type: retType as! FunctionTypeNode)
                }
                
                let pars:String = createFunctionParameters(pars: function.pars)
                
                var declaredFunction:String = type+" "+identifier
                declaredFunction.append("("+pars+")")
                
                
                declaredFunctions.append(declaredFunction)
                
                // type navn ( pars ) block
                let funcDecl:String = "\n"+type+" "+identifier+"("+pars+")"+createBlock(block: block)
                ret += funcDecl
            }
            
            
            return ret
        }
    }
    
    // Creates a generic function
    private func createGenericFunction(function: FunctionNode) -> String {
        guard let retType = function.retType else { return "" }
        
        var retGen = false
        if retType is NormalTypeNode {
            guard let retType = retType as? NormalTypeNode else { return "" }
            retGen = retType.generic
        }
        
        var str = ""

        // Vector function
        str += createGenericVectorFunction(function: function, retGen: retGen)
        
        return str
    }
    
    // Creates the generic std::vector<T> function (Called from 'createGenericFunction' to create the vector function)
    private func createGenericVectorFunction(function: FunctionNode, retGen: Bool) -> String {
        guard let retType = function.retType,
            let identifier = function.identifier,
            let block = function.block else { return "" }
        
        var vecFunc = "template<typename T>\n"
        
        // Return type
        if retGen {
            let tmpType = (retType as! NormalTypeNode).copy() as! NormalTypeNode
            tmpType.clearType = "T"
            
            vecFunc += createTypeString(type: tmpType)
        }
        else {
            vecFunc += createTypeString(type: retType as! NormalTypeNode)
        }
        
        vecFunc += " "+identifier
        
        // Parameters
        var vecPars = "("
        for n in 0 ..< function.pars.count {
            let par = function.pars[n]
            guard let pname = par.name else { continue }
            
            if par.type is NormalTypeNode {
                guard let ptype = par.type as? NormalTypeNode else { continue }
                if ptype.generic {
                    let tmpType = ptype.copy() as! NormalTypeNode
                    tmpType.clearType = "T"
                    
                    vecPars += createTypeString(type: tmpType)
                }
                else {
                    vecPars += createTypeString(type: ptype)
                }
                
                vecPars += " "+pname
            }
            else { // Function parameter
                guard let ptype = par.type as? FunctionTypeNode else { continue }
                
                let typeString = createFunctionTypeString(type: ptype)
                vecPars += typeString+" "+pname
            }
            
            if n != function.pars.count-1 {
                vecPars += ", "
            }
        }
        vecPars += ")"
        vecFunc += vecPars
        declaredFunctions.append(vecFunc)
        
        vecFunc += createBlock(block: block)
        
        return vecFunc
    }
    
    // Creates string with function parameters - (T1 n1, T2 n2 ... )
    private func createFunctionParameters(pars: [ParameterNode]) -> String {
        var str = ""
        
        for n in 0 ..< pars.count {
            let par = pars[n]
                
            guard let tmpType = par.type, let name = par.name else { continue }
            
            if tmpType is NormalTypeNode { // Normal type, just 'Type Name'
                
                if !par.variadic {
                    str += createTypeString(type: tmpType as! NormalTypeNode)+" "+name
                }
                else { // Variadic
                    let fix = (tmpType as! NormalTypeNode).copy() as! NormalTypeNode
                    fix.numNested = 1
                    
                    str += createTypeString(type: fix)+" "+name
                }
            }
            else if tmpType is FunctionTypeNode { // Function type, 'Type Name (Parameters)'
                
                let typeString = createFunctionTypeString(type: tmpType as! FunctionTypeNode)
                
                if !par.variadic {
                    str += typeString+" "+name
                }
                else {
                    str += "std::vector<"+typeString+"> "+name
                }
            }
            
            if n != pars.count-1 {
                str += ", "
            }
        }
        
        return str
    }
    
    
    // MARK: Block
    // Creates block - { [expr] }
    private func createBlock(block: BlockNode) -> String {
        
        var str = "{\n"
        
        // Save arguments!
        if doingMainBlock {
            str += "for(int n = 0; n < argc; n++) { std::string argS(argv[n]); std::vector<char> argV(argS.begin(), argS.end()); internal_arguments.push_back(argV); }\n"
            doingMainBlock = false
        }
        
        // Create expressions in block
        for expr in block.expressions {
            
            // Variadic parameters -> [lists]
            fixVariadicFunctions(expr: expr)
            
            // Do we need to declare something before the expression? (Function call parameters are declared before the call)
            str += createFunctionCallParameterDeclarations(expr: expr)
            
            // Create the expression itself
            str += createExpression(expr: expr)
        }
        
        str += "\n}\n"
        
        return str
    }
    
    
    // MARK: Function calls
    // Creates a function call - name "(" [expr] ")"
    private func createFunctionCall(call: FunctionCallNode) -> String {
        guard let identifier = call.identifier else { return "" }
        
        var parString = ""
        
        for n in 0 ..< call.parameters.count {
            let par = call.parameters[n]
            let expr = createExpression(expr: par)
            parString += expr
            
            if n != call.parameters.count-1 {
                parString += ", "
            }
        }
        
        let str = identifier+"("+parString+")"
        return str
    }
    
    // Transforms variadic parameters to array literals 
    // Changes the tree, replaces variadic arguments with a ArrayLiteral node instead containing the variadic arguments.
    private func fixVariadicFunctions(expr: Node) {
        if expr is FunctionCallNode { // Found function call, declare parameters and exchange them for the variablename
            guard let call = expr as? FunctionCallNode,
                let identifier = call.identifier else { return }
            
            for par in call.parameters {
                if par is FunctionCallNode {
                    fixVariadicFunctions(expr: par)
                }
            }
            
            // funcNode is the functionDeclaration
            guard let funcNode = ParserTables.shared.functionDeclarations[identifier] else { return }
            
            for n in 0 ..< funcNode.pars.count {
                let decPar = funcNode.pars[n]
                
                if decPar.variadic {
                    var litCont:[Node] = []
                    
                    if n == call.parameters.count { // Bail if no variadic arguments are present
                    }
                    else {
                        for i in n ..< call.parameters.count {
                            let par = call.parameters[i]
                            litCont.append(par)
                        }
                    }
                    
                    // Create array literal with variadic arguments
                    let newLit = ArrayLiteralNode(nodes: litCont)
                    var newCallPars:[Node] = []
                    for i in 0 ..< n {
                        newCallPars.append(call.parameters[i])
                    }
                    newCallPars.append(newLit)
                    call.parameters = newCallPars
                    
                    break
                }
            }

        }
        else if expr is ParenthesesExpression { // Possibly containing a function call
            if let tmp = (expr as! ParenthesesExpression).expression {
                fixVariadicFunctions(expr: tmp)
            }
        }
        else if expr is ExpressionNode { // expr OP expr, possible that expr is a function call
            guard let expr = expr as? ExpressionNode else { return }
            if let exp1 = expr.loperand, let exp2 = expr.roperand {
                fixVariadicFunctions(expr: exp1)
                fixVariadicFunctions(expr: exp2)
            }
        }
        else if expr is LetNode {
            guard let expr = expr as? LetNode else { return }
            for v in expr.vars {
                guard let vnode = v.value else { continue }
                fixVariadicFunctions(expr: vnode)
            }
        }
        else if expr is IfElseNode {
            guard let expr = expr as? IfElseNode, let econd = expr.condition else { return }
            fixVariadicFunctions(expr: econd)
        }
        else if expr is SwitchNode {
            guard let expr = expr as? SwitchNode else { return }
            for c in expr.cases {
                guard let cexpr = c.expr else { continue }
                fixVariadicFunctions(expr: cexpr)
            }
        }
    }
    
    // Called in 'createBlock', as to declare variables in function calls before the function call itself, at the start of a block
    // (Array and String literals are easier to handle as declarations, than they are in the calls, I think.)
    // Example: myFunc([1, 2, 3]) -> std::vector<int> tmp = {1, 2, 3}; myFunc(tmp);
    private func createFunctionCallParameterDeclarations(expr: Node) -> String {
        
        if expr is FunctionCallNode { // Found function call, declare parameters and exchange them for the variablename
            guard let fc = expr as? FunctionCallNode,
                  let ident = fc.identifier else { return "" }

            var str = ""
            // Iterate parameters (Some might need to be changed)
            for n in 0 ..< fc.parameters.count {
                let par = fc.parameters[n]
                
                // ArrayLiterals are replaced
                if par is ArrayLiteralNode {
                    guard let par = par as? ArrayLiteralNode else { continue }
                    
                    for c in par.contents {
                        str += createFunctionCallParameterDeclarations(expr: c)
                    }
                    
                    // Create a new name and refer it to itself in translation
                    let newName = ParserTables.shared.generateNewVariableName()
                    ParserTables.shared.nameTranslation[newName] = newName
                    
                    // Replace literal with reference to variable
                    let replacementNode = VariableNode(identifier: newName)
                    fc.parameters[n] = replacementNode
                    
                    // If the function is generic, guess the type. If not, find in function declaration
                    var type = ""
                    if ParserTables.shared.genericFunctionNames.contains(ident) {
                        type = "std::vector<"+guessType(node: par)+">"
                    }
                    else { // 'Normal' function
                        if let functionDecl = ParserTables.shared.functionDeclarations[ident] {
                            if n >= functionDecl.pars.count {
                                break
                            }
                            
                            //print("Funktionen \(ident) er ikke generisk, finder type i declaration!")
                            
                            if let defParType = functionDecl.pars[n].type as? NormalTypeNode {
                                if functionDecl.pars[n].variadic {
                                    type = "std::vector<"+createTypeString(type: defParType)+">"
                                }
                                else {
                                    type = createTypeString(type: defParType)
                                }
                            }
                        }
                    }
                    
                    str += type+" "+newName+" = "+createArrayLiteral(lit: par)+";"
                }
                else if par is StringLiteralNode { // String literal used as parameter, replace with std::vector<char>
                    guard let par = par as? StringLiteralNode else { continue }
                    
                    // Create a new name and refer it to itself in translation
                    let newName = ParserTables.shared.generateNewVariableName()
                    ParserTables.shared.nameTranslation[newName] = newName
                    
                    // Replace the literal with a reference to the variable
                    let replacementNode = VariableNode(identifier: newName)
                    fc.parameters[n] = replacementNode
                    
                    str += "std::vector<char> "+newName+" = "+createStringLiteral(string: par)+";"
                }
                else if par is FunctionCallNode { // Do the same for nested function calls
                    str += createFunctionCallParameterDeclarations(expr: par)
                }
                else if par is VariableNode {
                    guard let par = par as? VariableNode,
                          let identifier = par.identifier,
                          let funcDecl = ParserTables.shared.functionDeclarations[ident],
                          let tryCallingDecl = ParserTables.shared.functionDeclarations[identifier] else { return "" }
                    
                    // If this is a function type argument, pre-declare it.
                    if funcDecl.isFunctionType(index: n) {
                        
                        // Create a new name and refer it to itself in translation
                        let newName = ParserTables.shared.generateNewVariableName()
                        ParserTables.shared.nameTranslation[newName] = newName
                        
                        // Replace literal with reference to variable
                        let replacementNode = VariableNode(identifier: newName)
                        fc.parameters[n] = replacementNode
                        
                        let tmpStr = createFunctionTypeDefinition(function: tryCallingDecl)+" "+newName+" = "+identifier+";"
                        str += tmpStr
                    }

                }
            }
            
            return str
        }
        else if expr is ParenthesesExpression { // Possibly containing a function call
            if let tmp = (expr as! ParenthesesExpression).expression {
                return createFunctionCallParameterDeclarations(expr: tmp)
            }
        }
        else if expr is ExpressionNode { // expr OP expr, possible that expr is a function call
            guard let expr = expr as? ExpressionNode else { return "" }
            if let exp1 = expr.loperand, let exp2 = expr.roperand {
                var str = ""
                
                str += createFunctionCallParameterDeclarations(expr: exp1)
                str += createFunctionCallParameterDeclarations(expr: exp2)
                
                return str
            }
        }
        else if expr is LetNode {
            guard let expr = expr as? LetNode else { return "" }
            var str = ""
            for v in expr.vars {
                guard let vnode = v.value else { continue }
                str += createFunctionCallParameterDeclarations(expr: vnode)
            }
            
            return str
        }
        else if expr is IfElseNode {
            guard let expr = expr as? IfElseNode, let econd = expr.condition else { return "" }
            return createFunctionCallParameterDeclarations(expr: econd)
        }
        else if expr is SwitchNode {
            guard let expr = expr as? SwitchNode else { return "" }
            var str = ""
            
            for c in expr.cases {
                guard let cexpr = c.expr else { continue }
                str += createFunctionCallParameterDeclarations(expr: cexpr)
            }
            
            return str
        }
        
        return ""
    }
    
    func createFunctionTypeDefinition(function: FunctionNode) -> String {
        guard let retType = function.retType else { return "" }
        
        var str = "std::function<"
        
        // Ret
        if retType is NormalTypeNode {
            str += createTypeString(type: retType as! NormalTypeNode)
        }
        else {
            str += createFunctionTypeString(type: retType as! FunctionTypeNode)
        }
        
        str += "("
        
        // Pars
        for n in 0 ..< function.pars.count {
            let p = function.pars[n]
        
            guard let type = p.type else { continue }
            if type is NormalTypeNode {
                str += createTypeString(type: type as! NormalTypeNode)
            }
            else if type is FunctionTypeNode {
                str += createFunctionTypeString(type: type as! FunctionTypeNode)
            }
            
            if n != function.pars.count-1 {
                str += ", "
            }
        }
        
        str += ")>"
        
        return str
    }
    
    
    // MARK: Types (Normal and function types)
    // Creates a string from a normal type. Int becomes int, String becomse std::vector<char> and so on.
    private func createTypeString(type: NormalTypeNode) -> String {
        guard let clearType = type.clearType, let nested = type.numNested else { return "" }

        if nested == 0 {
            if let converted = typeConversions[clearType] {
                return converted
            }
            
            if ParserTables.shared.types.contains(clearType) {
                return "t_"+ParserTables.shared.createRename(forIdentifier: clearType)
            }
            
            return clearType // Må være objekt
        }
        
        var str = "const "
        
        for i in 0 ..< nested {
            str += "std::vector<"
            
            if i == nested-1 {
                if let converted = typeConversions[clearType] {
                    str += converted
                }
                else if ParserTables.shared.types.contains(clearType) {
                    str += "t_"+ParserTables.shared.createRename(forIdentifier: clearType)
                }
                else {
                    str += clearType
                }
            }
        }
        
        for _ in 0 ..< nested {
            str += ">"
        }
        
        return str
    }
    
    
    // Creates a function type string (Other syntax than normal types)
    private func createFunctionTypeString(type: FunctionTypeNode) -> String {
        
        guard let ret = type.ret else { return "" }
        var str = "std::function<"
        
        if ret is NormalTypeNode {
            str += createTypeString(type: ret as! NormalTypeNode)
        }
        else if ret is FunctionTypeNode {
            str += createFunctionTypeString(type: ret as! FunctionTypeNode)
        }
        
        str += "("
        
        for n in 0 ..< type.inputs.count {
            let t = type.inputs[n]
            
            if t is NormalTypeNode {
                str += createTypeString(type: t as! NormalTypeNode)
            }
            else if t is FunctionTypeNode {
                str += createFunctionTypeString(type: t as! FunctionTypeNode)
            }
            
            if n != type.inputs.count-1 {
                str += ", "
            }
        }
        
        str += ")"
        
        str += ">"
        
        return str
    }
    
    
    // MARK: Literals
    // Creates a string literal (Convert to vector, basically)
    func createStringLiteral(string: StringLiteralNode) -> String {
        guard let litContent = string.content else { return "" }
        var str = "{"

        var n = 0
        while n < litContent.characters.count {
            let c = litContent.charAt(index: n)
            
            // Escaping something?
            if c == "\\" {
                let nc = litContent.charAt(index: n+1)
                
                if nc == "\"" { // Quote, no need to escape
                    str += "'"+String(nc)+"'"
                }
                else { // Something else, like \n, \t and so.
                    str += "'"+String(c)+String(nc)+"'"
                }
                
                n += 1
            }
            else if c == "'" {
                str += "'\''"
            }
            else { // Regular char
                str += "'"+String(c)+"'"
            }
            
            if n != litContent.characters.count-1 {
                str += ", "
            }
            
            n += 1
        }
        
        str += "}"
        
        return str
    }
    
    // Laver array literal indhold (expr, expr ...)
    func createArrayLiteral(lit: ArrayLiteralNode) -> String {
        
        var str = "{"
        
        for n in 0 ..< lit.contents.count {
            let expr = lit.contents[n]
            str += createExpression(expr: expr)
            
            if n != lit.contents.count-1 {
                str += ", "
            }
        }
        
        str += "}"
        
        return str
    }
    
    // MARK: Expressions (1+2 (1+2) (true AND false) ... )
    // Laver par expression - "(" expr ")"
    private func createParenthesisExpression(expr: ParenthesesExpression) -> String {
        var str = "("
        str += createExpression(expr: expr.expression!)
        str += ")"
        return str
    }
    
    // Laver expression node  -  expr OP expr
    private func createExpressionNode(expr: ExpressionNode) -> String {
        guard let op = expr.op, let ops = op.op, let lop = expr.loperand, let rop = expr.roperand else { return "" }
        
        var str = ""
        str += createExpression(expr: lop)
        str += " "
        
        // Erstat operators hvis nødvendigt
        if let replace = opConversions[ops] {
            str += replace
        }
        else {
            str += ops
        }
        
        str += " "
        str += createExpression(expr: rop)
        
        return str
    }

    
    // Creates an expression (Covers all expression types)
    private func createExpression(expr: Node) -> String {
        if expr is IfElseNode {
            return createIfElseNode(ifElse: (expr as! IfElseNode))
        }
        else if expr is LetNode {
            return createLetNode(letN: (expr as! LetNode))
        }
        else if expr is SwitchNode {
            return createSwitchNode(node: (expr as! SwitchNode))
        }
        
        var retString = ""
        
        let shouldRet = shouldReturn(node: expr)
        if shouldRet {
            retString = "return "
        }
        
        switch expr {
        case is ExpressionNode:
            retString += createExpressionNode(expr: (expr as! ExpressionNode))
            break
            
        // Literals
        case is NumberLiteralNode:
            let exp = (expr as! NumberLiteralNode)
            if exp.floatValue != nil {
                retString += String(exp.floatValue!)
            }
            else if exp.intValue != nil {
                retString += String(exp.intValue!)
            }
            break
            
        case is VariableNode:
            if let id = (expr as! VariableNode).identifier {
                retString += id
            }
            break
            
        case is BooleanLiteralNode:
            retString += (expr as! BooleanLiteralNode).value
            break
            
        case is FunctionCallNode:
            retString += createFunctionCall(call: (expr as! FunctionCallNode))
            break
            
        case is ParenthesesExpression:
            retString += createParenthesisExpression(expr: (expr as! ParenthesesExpression))
            break
            
        case is StringLiteralNode:
            retString += createStringLiteral(string: (expr as! StringLiteralNode))
            break
            
        case is ArrayLiteralNode:
            retString += createArrayLiteral(lit: (expr as! ArrayLiteralNode))
            break
            
        case is CharLiteralNode:
            retString += "'"+(expr as! CharLiteralNode).content!+"'"
            break
            
        case is PropertyValueNode:
            guard let node = expr as? PropertyValueNode, let name = node.name else { break }
            
            if node.call == nil {
                guard let property = node.property else { break }
                retString += ParserTables.shared.createRename(forIdentifier: name)+"."+property
            }
            else {
                retString += ParserTables.shared.createRename(forIdentifier: name)+"."+createFunctionCall(call: node.call!)
            }
            break
            
        default:
            retString += ""
            break
        }
        
        if shouldRet { // End of expression
            retString += ";\n"
        }
        
        if expr is FunctionCallNode { // Side conditions should be ended too.
            let fc = expr as! FunctionCallNode
            guard let name = fc.identifier else { return retString }
            if ParserTables.shared.sideConditionFunctions.contains(name) {
                retString += ";\n"
            }
        }
        
        return retString
    }
    
    
    // MARK: Special expressions (let, switch, if-else)
    // Creates switch (if(){} else if(){} and so on)
    func createSwitchNode(node: SwitchNode) -> String {
        var str = ""
        
        for n in 0 ..< node.cases.count {
            let c = node.cases[n]
            
            if !(c.expr is ElseNode) { // Almindelig
                
                if n != 0 {
                    str += " else"
                }
                
                str += " if("
                str += createExpression(expr: c.expr!)
                str += ")"
                str += createBlock(block: c.block!)
            }
            else { // Sjovt nok, else!
                str += " else "
                str += createBlock(block: c.block!)
            }
        }
        
        return str
    }

    // Laver if-else - "if" expr block block
    private func createIfElseNode(ifElse: IfElseNode) -> String {
        guard let iblock = ifElse.ifBlock, let eblock = ifElse.elseBlock, let cond = ifElse.condition else { return "" }
        var str = ""
        
        str += "if("
        str += createExpression(expr: cond)
        str += ")\n"
        str += createBlock(block: iblock)
        str += "else "
        str += createBlock(block: eblock)
        
        return str
    }
    
    // Laver let - "let" [Type name "=" expr] block
    private func createLetNode(letN: LetNode) -> String {
        guard let block = letN.block else { return "" }
        

        // Lav funktionens indhold
        var str = "{"
        
        for v in letN.vars {
            guard let ttype = v.type, let name = v.name, let expr = v.value else { continue }
            
            // Normal type
            if ttype is NormalTypeNode {
                guard let ttype = ttype as? NormalTypeNode else { return "" }
                
                let type = createTypeString(type: ttype)
                str += type+" "+name+" = "
                str += createExpression(expr: expr)
            }
            else if ttype is FunctionTypeNode { // Function type
                guard let ttype = ttype as? FunctionTypeNode else { return "" }
                
                let typeString = createFunctionTypeString(type: ttype)
                
                str += typeString+" "+name+" = "+createExpression(expr: expr)
            }
            
            str += ";\n"
        }
        
        for bexpr in block.expressions {
            str += createExpression(expr: bexpr)
        }
        str += "}"
        
        return str
    }
    
    
    // MARK: Helpers
    // Burde vi returnere denne expression? (Nej hvis f.eks. if(1 == 2), skal jo ikke være if(return 1 == 2))
    private func shouldReturn(node: Node) -> Bool {
        
        var tmpNode:Node = node
        while tmpNode.parent != nil {
            let par = tmpNode.parent!
            
            if par is BlockNode {
                if node is FunctionCallNode { // Side condition?
                    let tmpNode = node as! FunctionCallNode
                    guard let name = tmpNode.identifier else { return true }
                    
                    if ParserTables.shared.sideConditionFunctions.contains(name) {
                        return false
                    }
                }
                
                return true
            }
            else if par is IfElseNode {
                return false
            }
            else if par is LetNode {
                return false
            }
            else if par is ParameterNode {
                return false
            }
            else if par is ExpressionNode {
                return false
            }
            else if par is FunctionCallNode {
                return false
            }
            else if par is ParenthesesExpression {
                return false
            }
            else if par is SwitchNode {
                return false
            }
            else if par is ArrayLiteralNode {
                return false
            }
            else {
                tmpNode = par
            }
        }
        
        return false
    }
    
    // Determine (gues..) the type of a literal (Array is guessing, rest is pretty straight forward) (Guess is fine. C++ compiler catches mistakes..)
    private func guessType(node: Node) -> String {

        if node is ArrayLiteralNode {
            guard let node = node as? ArrayLiteralNode else { return "" }
            if node.contents.count < 1 {
                return "void"
            }
            
            let fnode = node.contents[0]
            if fnode is CharLiteralNode {
                return "char"
            }
            else if fnode is NumberLiteralNode {
                if let fnode = fnode as? NumberLiteralNode {
                    if fnode.floatValue != nil {
                        return "float"
                    }
                    else if fnode.intValue != nil {
                        return "int"
                    }
                }
            }
            else if fnode is ArrayLiteralNode {
                let str = "std::vector<"+guessType(node: fnode)+">"
                return str
            }
            else if fnode is StringLiteralNode {
                return "std::vector<char>"
            }
        }
        else if node is NumberLiteralNode {
            if let node = node as? NumberLiteralNode {
                if node.floatValue != nil {
                    return "float"
                }
                else if node.intValue != nil {
                    return "int"
                }
            }
        }
        else if node is StringLiteralNode {
            return "std::vector<char>"
        }
        else if node is CharLiteralNode {
            return "char"
        }
        else if node is BooleanLiteralNode {
            return "bool"
        }
        
        return ""
    }
}
